# Generated by Django 3.2.8 on 2021-11-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evdokimov', '0002_rename_have been injured during vacation_player_injured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='favorite slot',
            new_name='favorite_slot',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='has an insurance',
            new_name='insurance',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='is_staff',
            new_name='is_senior',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='arrived with amount off people in hotel',
            new_name='with_amount',
        ),
    ]
