# Generated by Django 3.2.8 on 2021-11-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evdokimov', '0003_auto_20211107_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='hotel room number',
            new_name='hotel_room',
        ),
    ]
