# Generated by Django 3.2.8 on 2021-11-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evdokimov', '0005_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
